name: 17wanxiaoCheckin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 22 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: Pip install requests
      run: |
        pip3 install requests      
         
    - name: HealthCheckin
      run: |
        python3 17wanxiao.py <<EOF
        ${{secrets.SCKEY}}
        EOF
        
